; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][subdir] = "contrib"
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[devel][subdir] = "contrib"
projects[devel][version] = "1.5"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[features][subdir] = "contrib"
projects[features][version] = "2.2"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[rules][subdir] = "contrib"
projects[rules][version] = "2.7"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

; Themes
projects[omega][subdir] = "contrib"
projects[omega][version] = "4.3"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[tests][download][type] = ""
;projects[tests][download][url] = ""
;projects[tests][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
;projects[psr_0_test][download][type] = ""
;projects[psr_0_test][download][url] = ""
;projects[psr_0_test][type] = "module"

